name: Create and publish IPFS Build

on:
  push:
    branches: ["pulse"]

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - name: IPFS Publish
        id: IPFS
        uses: alexanderschau/ipfs-pinning-action@v1.0.0
        with:
          path_to_add: "./out" #Required
          endpoint: https://orange-causal-thrush-316.mypinata.cloud #Required
          access_token: ${{ secrets.PINATA_API_KEY }} #Required
          pin_name: "github-actions-test" #Optional
      # - run: curl -fsSL https://cli.pinata.cloud/install | bash
      # - name: Authenticate Pinata CLI
      #   env:
      #     PINATA_JWT: ${{ secrets.PINATA_JWT }}
      #   run: echo $PINATA_JWT > ~/.pinata-files-cli
      # - uses: aquiladev/ipfs-action@v0.1.3
      #   with:
      #     path: ./out
      #     service: pinata
      #     pinataKey: ${{ secrets.PINATA_API_KEY }}
      #     pinataSecret: ${{ secrets.PINATA_API_SECRET }}
      #     # pin: true
      #     pinName: "test"
